### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Danielx64** [fdocr/udl-server#19]
Hi

Is this project still alive and works?

Cheers

**Comment by fdocr** [comment]
Hi @Danielx64, it does still work. Deep linking to Universal links (iOS) in https://dev.to are handled with a server of these deployed to their hosting service. This way rate limit & block/allow list can be configured.

I stopped hosting the _"open and public server"_ (mentioned in the README) because I had no use case at the moment and wanted to stop that recurring expense I was covering on my own. Might come back to work on the refactor ideas & host it openly again if a use case in my projects needs it in the future.

I haven't kept track with dependabot updates in a while though. A PR to bump dependencies is coming up in a minute, thanks for the nudge to look back at this again 👍🏼 

If you have any questions about the project or a feature request please open a separate issue.
